name: Mirror F4S Wiki

on:
  schedule:
    - cron: '0 3 * * *'    # runs daily at 03:00 UTC
  workflow_dispatch:        # manual trigger

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: gh-pages

      - name: Install wget
        run: sudo apt update && sudo apt install -y wget

      - name: Mirror Google Site
        run: |
          rm -rf *
          mkdir mirror
          cd mirror
          wget --mirror --convert-links --adjust-extension --page-requisites --no-parent https://sites.google.com/view/f4swiki
          cd ..

      - name: Prepare Pages branch
        run: |
          # Move mirrored files to root (wget puts them in nested folders)
          mv mirror/sites.google.com/view/f4swiki/* .
          touch .nojekyll
          rm -rf mirror

      - name: Neutralize redirect logic
        run: |
          find . -name "*.js" -exec sed -i \
            -e 's/window\.location\s*=\s*["'\'']https:\/\/sites\.google\.com\/view\/test-website["'\''];//g' \
            -e 's/if\s*(window\.location\.hostname.*)//g' {} \;

      - name: Push to gh-pages branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Automated site mirror $(date)"
          git push https://${{ secrets.GH_TOKEN }}@github.com/calloffreedom/f4swiki.git
