name: Mirror F4S Wiki

on:
  schedule:
    - cron: '0 3 * * *'    # runs daily at 03:00 UTC
  workflow_dispatch:        # manual trigger

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install wget
        run: sudo apt update && sudo apt install -y wget

      - name: Mirror Google Site
        run: |
          rm -rf mirror
          mkdir mirror
          cd mirror
          wget --mirror --convert-links --adjust-extension --page-requisites --no-parent https://sites.google.com/view/f4swiki
          cd ..

      - name: Prepare Pages branch
        run: |
          # Move mirrored files to root (wget puts them in nested folders)
          mv mirror/sites.google.com/view/f4swiki/* .
          touch .nojekyll
          rm -rf mirror

      - name: Push to gh-pages branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan gh-pages
          git add .
          git commit -m "Automated site mirror $(date)"
          
      - name: Push changes
        run: |
          git push https://${{ secrets.GH_TOKEN }}@github.com/calloffreedom/f4swiki.git
