name: Mirror F4S Wiki

on:
  schedule:
    - cron: '0 3 * * *'    # runs daily at 03:00 UTC
  workflow_dispatch:        # manual trigger

jobs:
  mirror:
    runs-on: ubuntu-latest
    env:
      NEW_URL: "https://calloffreedom.github.io/f4swiki"
      OLD_URL: "https://sites.google.com/view/f4swiki"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: gh-pages

      - name: Install wget
        run: sudo apt update && sudo apt install -y wget

      - name: Mirror Google Site
        run: |
          rm -rf *
          mkdir mirror
          cd mirror
          wget --mirror --convert-links --adjust-extension --page-requisites --no-parent https://sites.google.com/view/f4swiki
          cd ..

      - name: Prepare Pages branch
        run: |
          # Move mirrored files to root (wget puts them in nested folders)
          mv mirror/sites.google.com/view/f4swiki/* .
          touch .nojekyll
          rm -rf mirror

      - name: Strip only the 5th <script> block
        run: |
          find . -type f -name "*.html" | while read file; do
            awk '
              BEGIN { count=0 }
              /<script[^>]*>/ {
                count++
              }
              {
                if (count==5 && inside==1) {
                  # we are inside the 5th script: skip every line until </script>
                  if (/<\/script>/) { inside=0 }
                  next
                }
              }
              count==5 && /<script[^>]*>/ { inside=1; next }
              { print }
            ' "$file" > tmp && mv tmp "$file"
          done

      - name: Push to gh-pages branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Automated site mirror $(date)"
          git push https://${{ secrets.GH_TOKEN }}@github.com/calloffreedom/f4swiki.git
