name: Mirror F4S Wiki

on:
  push:               # ✅ runs whenever you push to this repo
  schedule:
    - cron: '0 3 * * *'   # ✅ runs daily at 03:00 UTC
  workflow_dispatch:      # ✅ can trigger manually

permissions:
  contents: write         # ✅ lets Actions push back to the repo

jobs:
  mirror:
    runs-on: ubuntu-latest
    env:
      NEW_URL: "https://calloffreedom.github.io/f4swiki"
      OLD_URL: "https://sites.google.com/view/f4swiki"

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Install wget
        run: sudo apt update && sudo apt install -y wget

      - name: Mirror Google Site
        run: |
          # ✅ keep .github folder intact, wipe everything else
          find . -mindepth 1 ! -regex '^./\.git.*' ! -path './.github*' -exec rm -rf {} +
          mkdir mirror
          cd mirror
          wget --mirror --convert-links --adjust-extension --page-requisites --no-parent https://sites.google.com/view/f4swiki
          cd ..

      - name: Prepare Pages branch
        run: |
          # Move mirrored files into repo root
          mv mirror/sites.google.com/view/f4swiki/* .
          touch .nojekyll
          rm -rf mirror

      - name: Strip only the 5th <script> block
        run: |
          find . -type f -name "*.html" | while read file; do
            perl -0777 -pe '
              my $count = 0;
              s{
                (<script\b[^>]*>.*?</script>)
              }{
                ++$count == 5 ? "" : $1
              }gsex
            ' "$file" > tmp && mv tmp "$file"
          done

      - name: Commit and push updated site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated site mirror $(date)" || echo "No changes to commit"
          git push https://${{ secrets.GH_TOKEN }}@github.com/calloffreedom/f4swiki.git
